openapi: 3.0.0
info:
  description: 'https://developer.ingage.jp/'
  version: 1.0.0
  title: Re:lation API

servers:
  - url: https://#{subdomain}.relationapp.jp/api/v2
    variables:
      subdomain:
        default: '*'
        description: ご利用のサブドメイン

tags:
  - name: message_box
    description: 受信箱
  - name: ticket
    description: チケット
  - name: customer
    description: アドレス帳

security:
  - bearer: []

paths:
  /message_boxes:
    get:
      tags:
        - message_box
      summary: 一覧取得
      responses:
        '200':
          description: 一覧取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MessageBox'

  /{message_box_id}/customers:
    post:
      parameters:
        - name: message_box_id
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
          schema:
            type : integer
            format: int64
            minimum: 1
      tags:
        - message_box
      summary: 登録
      responses:
        '200':
          description: 登録
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
  /{message_box_id}/records:
    post:
      tags:
        - message_box
      summary: 応答メモ作成
      parameters:
        - name: message_box_id
          in: path
          required: true
          description: 受信箱ID(数字)
          schema:
            type: integer
        - name: ticket_id
          in: query
          description: チケットID
          schema:
            type: integer
        - name: subject
          required: true
          description: 件名
          in: query
          schema:
            type: string
        - name: status_cd
          in: query
          description: ステータス
          schema:
            type: string
            enum:
            - open
            - ongoing
            - closed
            - unwanted
            - trash
            - spam
            - deleted
        - name: operated_at
          in: query
          description: 対応日時(ISO 8601 形式。過去の日時のみ。)
          required: true
          schema:
            type : string
            format: date
            example: 2022-09-11
        - name: operator
          required: true
          description: 対応者のメンション名
          in: query
          schema:
            type : string
        - name: duration
          required: true
          description: 対応時間(0〜1440の数値。分単位。)
          in: query
          schema:
            type: integer
        - name: body
          required: true
          description: 本文
          in: query
          schema:
            type: string
        - name: customer_email
          in: query
          description: 顧客メールアドレス
          schema:
            type: string
        - name: customer_tel
          in: query
          description: 顧客電話番号
          schema:
            type: string
        - name: icon_cd
          in: query
          description: 対応種別
          schema:
            type: string
            enum:
            - received_phone
            - called_phone
            - meeting
            - sales
            - postal
            - note
        - name: is_html
          in: query
          schema:
            type: boolean
        - name: assignee
          in: query
          schema:
            type: string

      responses:
        '200':
          description: 応対メモ作成
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Record'

components:
  schemas:
    MessageBox:
      title: 受信箱
      description: 受信箱
      type: object
      properties:
        message_box_id:
          type: integer
          format: int64
        name:
          type: integer
          format: int64
        color:
          type: integer
          format: int32
        last_updated_at:
          type: string
          format: date-time
    Customer:
      title: アドレス帳
      description: アドレス帳
      type: object
      properties:
        last_name:
          type: string
        first:
          type: string
    Record:
      title: 応答メッセージ
      type: object
      properties:
        message_id:
          type: integer
        ticket_id:
          type: integer

  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Re:lation 画面右上ギアアイコンより、[API トークン設定] でアクセストークンを 発行・確認することができます。
