=begin
#Relation API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RelastionClient::MessageBoxApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'MessageBoxApi' do
  before do
    # run before each test
    @api_instance = RelastionClient::MessageBoxApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MessageBoxApi' do
    it 'should create an instance of MessageBoxApi' do
      expect(@api_instance).to be_instance_of(RelastionClient::MessageBoxApi)
    end
  end

  # unit tests for message_box_id_customers_post
  # 登録
  # @param message_box_id Parameter description in CommonMark or HTML.
  # @param [Hash] opts the optional parameters
  # @return [Array<Customer>]
  describe 'message_box_id_customers_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for message_boxes_get
  # 一覧取得
  # @param [Hash] opts the optional parameters
  # @return [Array<MessageBox>]
  describe 'message_boxes_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
