=begin
#Re:lation API

#https://developer.ingage.jp/

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.1.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RelationClient::Record
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RelationClient::Record do
  let(:instance) { RelationClient::Record.new }

  describe 'test an instance of Record' do
    it 'should create an instance of Record' do
      expect(instance).to be_instance_of(RelationClient::Record)
    end
  end
  describe 'test attribute "message_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "ticket_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
